title: Afronomy
description: Radio Interferometric Data Processing.
show_downloads: true
google_analytics: 
theme: jekyll-theme-tactile
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
